Run fonttools against TTF files to save 300KB~
libretro/retroarch-assets pull request #473
Opened 2024-04-01 22:31 UTC by C0rn3j

Conversation in #471

This needs testing before merge.

2024-04-15 16:40 UTC, baxysquare approved these changes
I approve of this PR, as it will reduce the font sized in the repository. But I don't currently have an environment to test it in.  We could really use some help from @LibretroAdmin or another top contributor to the main project.

2024-04-19 03:06 UTC, RobLoach approved these changes
Seems to work on Linux with XMB. I don't have any other devices to really test this on, but I assume it's okay?

2024-04-19 03:07 UTC, RobLoach commented on devtools/palettes/pdf/flatux-palette.pdf
You're touching this file in the other PR at https://github.com/libretro/retroarch-assets/pull/472 too... Related?

2024-05-30 22:07 UTC, RobLoach requested changes
Looks like a conflict since your last commit?

2024-06-03 14:22 UTC, C0rn3j commented
Had to hard reset the fork, but it shouldn't conflict anymore.

2024-12-30 23:26 UTC, LibretroAdmin commented
We'll try this. If it causes issues we will have to revert it.

2024-12-30 23:26 UTC, merged